# Generated by Django 4.2.1 on 2023-08-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('tname', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=10)),
            ],
        ),
    ]
